### ISSUE TITLE
hubot-rss-readerを動かす

### ISSUE THREAD

**Issue by sota1235** [sota1235/slack-fresh15-hubot#1]
room名の#が原因っぽい

**Comment by shokai** [comment]
hubot-slack npmとslack-client npmが古いとroom名に#含まれてると動かないです（#が無いと動かない、だったかも）
私のプルリクによって修正されてるので最新にあげるがよいぞ

**Comment by shokai** [comment]
あれ、でもhubot-slack最新版だ

**Comment by sota1235** [comment]
むーん…なんでしょうこれ。つらい

**Comment by shokai** [comment]
robot.errorとか、DEBUG=*とかどうかな

**Comment by sota1235** [comment]
```
istyle-fresh15-hubot> istyle-fresh15-hubot rss add https://github.com/sota1235.atom
[Wed Apr 29 2015 16:01:46 GMT+0900 (JST)] INFO hubot-rss-reader: add https://github.com/sota1235.atom
[Wed Apr 29 2015 16:01:46 GMT+0900 (JST)] ERROR TypeError: Object https://github.com/sota1235.atom has no method 'then'
  at TextListener.callback (/Users/sota1235/Documents/sota1235/github/slack-hubot-fresh15/node_modules/hubot-rss-reader/scripts/hubot-rss-reader.coffee:106:5, <js>:145:40)
  at TextListener.Listener.call (/Users/sota1235/Documents/sota1235/github/slack-hubot-fresh15/node_modules/hubot/src/listener.coffee:27:7, <js>:23:14)
  at Robot.receive (/Users/sota1235/Documents/sota1235/github/slack-hubot-fresh15/node_modules/hubot/src/robot.coffee:197:9, <js>:143:33)
  at Shell.Adapter.receive (/Users/sota1235/Documents/sota1235/github/slack-hubot-fresh15/node_modules/hubot/src/adapter.coffee:66:5, <js>:47:25)
  at [object Object].listener (/Users/sota1235/Documents/sota1235/github/slack-hubot-fresh15/node_modules/hubot/src/adapters/shell.coffee:48:7, <js>:92:22)
  at [object Object].Cli.parse (/Users/sota1235/Documents/sota1235/github/slack-hubot-fresh15/node_modules/hubot/node_modules/cline/index.js:320:35)
  at [object Object].<anonymous> (/Users/sota1235/Documents/sota1235/github/slack-hubot-fresh15/node_modules/hubot/node_modules/cline/index.js:182:18)
  at [object Object].defaultFn (/Users/sota1235/Documents/sota1235/github/slack-hubot-fresh15/node_modules/hubot/node_modules/cline/index.js:53:13)
  at [object Object].fn (/Users/sota1235/Documents/sota1235/github/slack-hubot-fresh15/node_modules/hubot/node_modules/cline/index.js:217:23)
  at Interface.<anonymous> (/Users/sota1235/Documents/sota1235/github/slack-hubot-fresh15/node_modules/hubot/node_modules/cline/index.js:148:18)
  at Interface.emit (events.js:95:17)
  at Interface._onLine (readline.js:202:10)
  at Interface._line (readline.js:531:8)
  at Interface._ttyWrite (readline.js:760:14)
  at ReadStream.onkeypress (readline.js:99:10)
  at ReadStream.emit (events.js:98:17)
  at emitKey (readline.js:1095:12)
  at ReadStream.onData (readline.js:840:14)
  at ReadStream.emit (events.js:95:17)
  at ReadStream.<anonymous> (_stream_readable.js:764:14)
  at ReadStream.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:426:10)
  at emitReadable (_stream_readable.js:422:5)
  at readableAddChunk (_stream_readable.js:165:9)
  at ReadStream.Readable.push (_stream_readable.js:127:10)
  at TTY.onread (net.js:528:21)
```

って言われました。masuilabで動いてるのになぜだあああああ

**Comment by shokai** [comment]
これはcoffee-scriptが古いので最新を入れて下さい

**Comment by sota1235** [comment]
動きました。あざます:pray:

**Comment by shokai** [comment]
あとついでだけどherokuのnodeは今app作ったらceder-14 stack(node 0.12が動いてる)が作られるはずなので、travisciの設定も0.12にしたほうがいいと思いまーす

**Comment by sota1235** [comment]
知らなかった。あざます！
